import Head from "next/head";
import Card from "../components/card";
import styles from "../styles/Home.module.css";
//context
import { useContext } from "react";
import { ThemeContext } from "../components/ThemeContext";
import Search from "../components/search";
//context
const myLoader = ({ src, width, quality }) => {
  return `${src}`;
};
function Home({ data }) {
  const [theme] = useContext(ThemeContext);

  return (
    <div className={theme && "dark"}>
      <Head>
        <title>my shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-12 pb-12">
        <div className="grid grid-cols-10 gap-2 ">
          {/* card */}
          <div className="col-span-9 lg-ex:col-span-8 ">
            <Card data={data} />
          </div>
          {/* sidebar */}
          <div className="hidden col-span-2 lg-ex:block">
            <div className="fixed right-2 ">
              <Search />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
//*getServerSideProps
export async function getServerSideProps() {
  const res = await fetch("https://fakestoreapi.com/products");
  const products = await res.json();
  return {
    props: {
      data: products,
    },
  };
}

export default Home;
// getStaticProps(ssg);
// getStaticPaths(ssg);
//
// getServerSideProps(ssr)
